### ISSUE TITLE
请增加固定标签页排除分组开关....

### ISSUE THREAD

**Issue by Noah1995** [marwincn/auto-group-tabs#10]
请增加【一键分组所有Tabs】排除固定标签页分组开关....
如图
![image](https://user-images.githubusercontent.com/25548230/182937940-4500c2fb-c860-4ae4-8058-ce20d5b40588.png)

**Comment by marwincn** [comment]
最新版本已作为bug修复，插件不再会对固定标签页进行分组，商店版本为1.1.5 #13

**Comment by Noah1995** [comment]
> 最新版本已作为bug修复，插件不再会对固定标签页进行分组，商店版本为1.1.5 #13

![image](https://user-images.githubusercontent.com/25548230/204135773-108b89ae-6fa3-4205-a9e1-817cb3ebef9e.png)
还有这个保存组能不能
你这默认也加个开关
